eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762

spring:
  application:
    name: zuul
zuul:
  #忽略那些不匹配的服务
  #ignoredServices: '*'
  #忽略那些不匹配的服务:包含/admin/
  #ignoredServices:  /**/admin/**
  routes:
    legacy:
      path: /**
      url: https://www.toutiao.com
  filter:
    root: "groovy/filters"
    refreshInterval: 5

#使用httpclient
ribbon:
  httpclient:
    enabled: true
  ReadTimeout: 7000
  ConnectTimeout: 7000

#安全验证关闭
management:
  security:
    enabled: false