eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password :
    encode: UTF-8
    timeout: 6000
    pool:
      max-active: 100
      max-wait: -1
      max-idle: 10
      min-idle: 5


